version: '3.4'

services:
  dailypythonjourney:
    image: dailypythonjourney
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 day_01/bmi_calculator.py "]
    ports:
      - 5678:5678
