name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python version
        run: python --version

      - name: Check pytest version
        run: pytest --version

      - name: List files in the repository
        run: ls -R

      - name: List files in the tests directory
        run: ls -R tests/

      - name: Run tests with specific pattern
        run: pytest tests/test_*.py --maxfail=1 --disable-warnings -v

      - name: Run flake8
        run: flake8 .

      - name: Run mypy
        run: mypy .

      - name: Notify Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            CI/CD Status: ${{ job.status }}
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}

      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/master'
        run: |
          heroku login -i
          git push heroku master

      - name: Run coverage
        run: |
          pip install pytest-cov
          pytest --cov=day_01 --maxfail=1 --disable-warnings -v
